apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: resume-web
  name: resume-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: resume-web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
          - name: content
            mountPath: /usr/share/nginx/html/
        livenessProbe:
          httpGet:
            path: /
            port: 80

      volumes:
      - name: content
        hostPath:
          path: /home/peter/public
status: {}
